name: Build with goreleaser

on:
  push:
    branches: [ master, devel ]
    tags:
      - "*"
  pull_request:
    branches: [ master, devel ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4

    - name: Build release
      uses: goreleaser/goreleaser-action@v4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build snapshot
      uses: goreleaser/goreleaser-action@v4
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      with:
        version: latest
        args: release --clean --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@v3
      with:
        name: PR-DNSd
        path: dist/*
