name: Build Go artifacts

on:
  push:
    branches: [ master, devel ]
    tags:
      - "*"
  pull_request:
    branches: [ master, devel ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PR-DNSd
        path: dist/*
